parser: "@typescript-eslint/parser"

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict

parserOptions:
  project:
    - ./packages/*/tsconfig.json

plugins:
  - "@typescript-eslint"
